### ISSUE TITLE
What's this about?

### ISSUE THREAD

**Issue by ppaluchowski64** [KaaBEL/Deltarealm-b64-keys#6]
Is this a game or what is it? I do not understand this.

**Comment by KaaBEL** [comment]
@IndianaJonesTutor
Yes, Deltarealm is game. It's space themed sandbox open world mobile game (currently availible on android) developed by RizenPlanetStudio. It's only alpha testing (version 0.1.2) stopped in development while the developer focuses on releasing other game Droneboi 2.

I made this tool so players can convert their creations to base64 codes and share them through shorter text key, as it is in other Droneboi games.

**Comment by ppaluchowski64** [comment]
So this repository isn't a game, it's just something that turns your ships into base64?

**Comment by KaaBEL** [comment]
Exactly. _Edit: except it's not just something, but a powerfull tool._

**Comment by ppaluchowski64** [comment]
Oh okay. :) I see. Multi lines.
